apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: test-app 
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: tomcat
        image: dtr.nagarro.com:443/my-app:46
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: test-app
  ports:
  - name: port8080
    protocol: TCP
    nodePort: {{ .Values.nodePort }}
    port: 80
    targetPort: 80

